porch/views/groups.py
# -*- coding: utf-8 -*-
'''
    :codeauthor: :email:`Pedro Algarvio (pedro@algarvio.me)`
    :copyright: © 2013 by the SaltStack Team, see AUTHORS for more details.
    :license: Apache 2.0, see LICENSE for more details.


    porch.views.groups
    ~~~~~~~~~~~~~~~~~

    Minimal group management
'''

# Import POrch libs
from porch.forms import *
from porch.application import *


# ----- Blueprints & Menu Entries --------------------------------------------------------------->
groups = Blueprint('groups', __name__, url_prefix='/groups')

main_category_link = main_nav.add_menu_entry(
    _('Groups'), 'groups.index', classes='sensible', priority=-40,
    visiblewhen=check_wether_is_admin
)

groups_nav = build_context_nav('groups_view_nav')
groups_nav.add_menu_entry(
    glyphiconer('plus') + _('New Group'), 'groups.new', priority=100,
    visiblewhen=check_wether_is_admin
)
# <---- Blueprints & Menu Entries ----------------------------------------------------------------


# ----- Forms ----------------------------------------------------------------------------------->
# <---- Forms ------------------------------------------------------------------------------------


# ----- Views ----------------------------------------------------------------------------------->
@groups.route('/')
@administrator_permission.require(403)
def index():
    return render_template('groups/index.html', groups=Group.query.all())


@groups.route('/new')
@administrator_permission.require(403)
def new():
    pass


@groups.route('/edit/<group_id>', methods=('GET', 'POST'))
@administrator_permission.require(403)
def edit(group_id):
    pass


@groups.route('/edit/<group_id>', methods=('GET', 'POST'))
@administrator_permission.require(403)
def delete(group_id):
    pass
# <---- Views ------------------------------------------------------------------------------------

porch/templates/groups/index.html
{% extends "groups/layout.html" %}

{% block title %}{% trans%}Groups{% endtrans %}{% endblock %}

{% block contents %}
{% if groups %}
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th class="expand">Name</th>
        <th class="narrow">Members</th>
        <th class="narrow">Actions</th>
      </tr>
    </tead>
    <tbody class="table-hover">
      {%- for group in groups %}
      <tr>
        <td>{{ group.name }}</td>
        <td class="narrow">{{ group.accounts.count() }}</td>
        <td class="narrow">
          <a class="btn" href={{ url_for('groups.delete', group_id=group.id) }}
             title="{% trans %}Delete Group{% endtrans %}">{{ glyphiconer('trash') }}</a>
          <a class="btn" href={{ url_for('groups.edit', group_id=group.id) }}
             title="{% trans %}Edit Group{% endtrans %}">{{ glyphiconer('edit') }}</a>
        </td>
      </tr>
      {%- endfor %}
    </tbody>
  </table>
</div>
{% else %}
<p>No groups available</p>
{% endif %}
{% endblock %}

porch/templates/groups/layout.html
{% extends "_formbase.html" %}

{% block render_context_nav %}
{{ menubuilder.render('groups_view_nav') }}
{% endblock %}