porch/views/users.py
# -*- coding: utf-8 -*-
'''
    :codeauthor: :email:`Pedro Algarvio (pedro@algarvio.me)`
    :copyright: © 2013 by the SaltStack Team, see AUTHORS for more details.
    :license: Apache 2.0, see LICENSE for more details.


    porch.views.users
    ~~~~~~~~~~~~~~~~~

    Minimal user management
'''

# Import POrch libs
from porch.forms import *
from porch.application import *


# ----- Blueprints & Menu Entries --------------------------------------------------------------->
users = Blueprint('users', __name__, url_prefix='/users')

main_category_link = main_nav.add_menu_entry(
    _('Users'), 'users.index', classes='sensible', priority=-50,
    visiblewhen=check_wether_is_admin
)

users_nav = build_context_nav('users_view_nav')
# <---- Blueprints & Menu Entries ----------------------------------------------------------------


# ----- Forms ----------------------------------------------------------------------------------->
# <---- Forms ------------------------------------------------------------------------------------


# ----- Views ----------------------------------------------------------------------------------->
@users.route('/')
@administrator_permission.require(403)
def index():
    return render_template('users/index.html', users=Account.query.all())


@users.route('/permissions/<user_id>')
@administrator_permission.require(403)
def perms():
    return render_template('users/index.html', users=Account.query.all())
# <---- Views ------------------------------------------------------------------------------------

porch/templates/users/index.html
{% extends "users/layout.html" %}

{% block title %}{% trans%}Users{% endtrans %}{% endblock %}

{% block contents %}
{% if users %}
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Username</th>
        <th class="expand">Name</th>
        <th>Last Access</th>
        <th>Register Date</th>
        <th>Actions</th>
      </tr>
    </tead>
    <tbody class="table-hover">
      {%- for user in users %}
      <tr>
        <td>{{ user.login }}</td>
        <td>{{ user.name }}</td>
        <td>{{ user.last_login | datetimeformat }}</td>
        <td>{{ user.register_date | datetimeformat }}</td>
        <td class="narrow">
          <a class="btn" href={{ url_for('users.perms', user_id=user.id) }}
             title="{% trans %}User Permissions{% endtrans %}">{{ glyphiconer('lock') }}</a>
        </td>
      </tr>
      {%- endfor %}
    </tbody>
  </table>
</div>
{% else %}
<p>No users available</p>
{% endif %}
{% endblock %}

porch/templates/users/layout.html
{% extends "_formbase.html" %}

{% block render_context_nav %}
{{ menubuilder.render('users_view_nav') }}
{% endblock %}